"""Libellés courts et propres des chapitres HS 01-97, pour les graphiques et
les coupes. Les descriptions officielles du Census sont trop longues pour un
axe; celles-ci sont éditoriales, stables, et tiennent en moins de 26 signes."""

CHAPTER_LABELS = {
    "01": "live animals",
    "02": "meat",
    "03": "fish & seafood",
    "04": "dairy & eggs",
    "05": "other animal products",
    "06": "plants & flowers",
    "07": "vegetables",
    "08": "fruit & nuts",
    "09": "coffee, tea & spices",
    "10": "cereals",
    "11": "milling products",
    "12": "oilseeds",
    "13": "gums & resins",
    "14": "other veg. products",
    "15": "fats & oils",
    "16": "prepared meat & fish",
    "17": "sugar",
    "18": "cocoa",
    "19": "baked goods",
    "20": "prepared produce",
    "21": "misc. food",
    "22": "beverages & spirits",
    "23": "animal feed",
    "24": "tobacco",
    "25": "salt, stone & cement",
    "26": "ores",
    "27": "mineral fuels",
    "28": "inorganic chemicals",
    "29": "organic chemicals",
    "30": "pharmaceuticals",
    "31": "fertilizers",
    "32": "dyes & paints",
    "33": "cosmetics & perfumery",
    "34": "soaps & waxes",
    "35": "glues & enzymes",
    "36": "explosives & matches",
    "37": "photographic goods",
    "38": "misc. chemicals",
    "39": "plastics",
    "40": "rubber",
    "41": "raw hides & leather",
    "42": "leather goods",
    "43": "furskins",
    "44": "wood",
    "45": "cork",
    "46": "basketry",
    "47": "wood pulp",
    "48": "paper",
    "49": "printed matter",
    "50": "silk",
    "51": "wool",
    "52": "cotton",
    "53": "other plant fibers",
    "54": "synthetic filaments",
    "55": "synthetic staple fibers",
    "56": "nonwovens & cordage",
    "57": "carpets",
    "58": "special fabrics",
    "59": "coated fabrics",
    "60": "knitted fabrics",
    "61": "apparel, knit",
    "62": "apparel, woven",
    "63": "other textiles",
    "64": "footwear",
    "65": "headgear",
    "66": "umbrellas",
    "67": "feathers & plumes",
    "68": "stone & cement articles",
    "69": "ceramics",
    "70": "glass",
    "71": "jewelry & precious",
    "72": "iron & steel",
    "73": "iron & steel articles",
    "74": "copper",
    "75": "nickel",
    "76": "aluminum",
    "78": "lead",
    "79": "zinc",
    "80": "tin",
    "81": "other base metals",
    "82": "tools & cutlery",
    "83": "misc. metal articles",
    "84": "machinery",
    "85": "electronics",
    "86": "railway",
    "87": "vehicles",
    "88": "aircraft",
    "89": "ships",
    "90": "optics & instruments",
    "91": "clocks & watches",
    "92": "musical instruments",
    "93": "arms & ammunition",
    "94": "furniture & bedding",
    "95": "toys & games",
    "96": "misc. manufactures",
    "97": "art & antiques",
}


def label(ch, fallback=""):
    return CHAPTER_LABELS.get(str(ch).zfill(2), (fallback or str(ch))[:26])
